name: Feature Branch CI

on:
  push:
    branches:
      - 'dev/**'

jobs:
  lightweight-checks:
    name: Run Lightweight Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache npm dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Start server in background
        run: npm start &
        
      - name: Wait for server
        uses: ./.github/actions/wait-for-server
        with:
          url: http://localhost:3000/health
          timeout_seconds: 60
          interval_seconds: 5

        
      - name: Run tests
        # sanity only, no coverage report. 
        run: npm test

      - name: Docker Build Check
        run: docker build . -t test-build