name: Manual Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'The full Git SHA of the version you want to restore'
        required: true
        type: string
      environment:
        description: 'The environment to roll back (e.g., production)'
        required: true
        type: choice
        options:
          - production
          - staging

jobs:
  rollback-deploy:
    name: Rollback ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    environment:
      # Use the environment selected by the user
      name: ${{ github.event.inputs.environment }}

    steps:
      - name: Deploy previous version
        # Docker image from the registry, that corresponds to the provided commit SHA.
        # It then performs a standard zero-downtime deployment using that known-good image.
        run: |
          echo "Starting rollback of the ${{ github.event.inputs.environment }} environment..."
          IMAGE_TAG="your-app-name:${{ github.event.inputs.commit_sha }}"
          echo "Targeting previously-approved image: $IMAGE_TAG"

          # ======================= PSEUDO-CODE FOR A ROLLBACK DEPLOYMENT ======================
          #
          # echo "Executing blue-green deployment with rollback image..."
          #
          # `blue_green_deployment.sh ` : The script would pull the old image and safely switch traffic back to it.
          # performing a monitoring of the ports, updating the inactive one,
          # switch the traffic to the updated, and update the new inactive one.
          # sh `blue_green_deployment.sh `
          #
          # echo "Rollback to version ${{ github.event.inputs.commit_sha }} is complete."
          # =======================================================================================