name: Manual Rollback from Commit

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'The full commit SHA to roll back to (e.g., a1b2c3d4...)'
        required: true
        type: string

permissions:
  contents: read

jobs:
  build-and-test-rollback:
    name: Build and Test Rollback
    runs-on: ubuntu-latest
    environment: production # Simulating a rollback to a production-like environment
    steps:
      - name: Checkout specific commit
        uses: actions/checkout@v4
        with:
          # This is the key step: check out the exact code from the specified commit
          ref: ${{ github.event.inputs.commit_sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image from old source
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true # Load the image directly into the runner's Docker daemon
          tags: your-app-name:rollback-${{ github.event.inputs.commit_sha }}

      - name: Create .env file for Docker Compose
        run: echo "WEB_IMAGE_TAG=${{ steps.build.outputs.digest }}" > .env

      - name: Run the container using Docker Compose
        run: docker compose up -d

      - name: Verify Container Health
        id: health_check
        run: |
            echo "startign health check"
            for i in {1..5}
            do
                status=$(docker inspect --format '{{.State.Health.Status}}' test_container)
                echo "Attempt $i: Container status is $status"
                if [ "$status" = "healthy" ]; then
                echo "Container is healthy! "
                exit 0
                fi
                echo "Attempt $i failed. Retrying in 1 seconds..."
                sleep 3
            done
            echo "Container did not become healthy in time."
            docker logs test_container > docker_log.txt        
            exit 1

      - name: Upload Docker logs on failure
        if: failure() && steps.health_check.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: rollback-docker-logs
          path: docker_log.txt

      - name: Stop the container
        if: always()
        run: docker stop test_container

    #   - name: Send Slack Notification on Success
    #     if: success()
    #     run: |
    #       curl -X POST -H 'Content-type: application/json' \
    #       --data '{"text":"⏪ Simulated production has been successfully rolled back to commit `${{ github.event.inputs.commit_sha }}`.\nTriggered by: `${{ github.actor }}`"}' \
    #       ${{ secrets.SLACK_WEBHOOK_URL }}

    #   - name: Send Slack Notification on Failure
    #     if: failure()
    #     run: |
    #       curl -X POST -H 'Content-type: application/json' \
    #       --data '{"text":"❌ Simulated production rollback to commit `${{ github.event.inputs.commit_sha }}` FAILED.\nTriggered by: `${{ github.actor }}`"}' \
    #       ${{ secrets.SLACK_WEBHOOK_URL }}